### PR TITLE
Transitive closure

### PR DESCRIPTION
**Pull request by e-avidan**

### CODE REVIEW

**Comment by corwin-of-amber** [comment]
Cool!

Can you change the name of `MatchDefinition` to `PatternDefinition`? I was confused by it because it described what is being sought, not what is found.

Now let's try to implement lexical scope resolution using these patterns 🤓

**Comment by e-avidan** [comment]
@corwin-of-amber missed it cause of no notifications 😅 

Right on about the name, will change it
Can you give me an example for what you'd expect the lexical scope resolution to be like?

**Comment by e-avidan** [comment]
Ok pushed the fix + the apple fell and I understood what you meant by scope resolution, will do :)

**Comment by corwin-of-amber** [comment]
Cool! 🚀

**Pull request merged**
